name: Dockerhub-release

env:
  IMAGE_NAME: antlafarge/jdownloader

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Release:
    strategy:
      matrix:
        openjdkVersion: [openjdk8, openjdk17, openjdk21]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: alpine-${{ matrix.openjdkVersion }}, ubuntu-${{ matrix.openjdkVersion }}, ${{ matrix.openjdkVersion }}
        run: |
          docker pull ${{ env.IMAGE_NAME }}:dev-alpine-${{ matrix.openjdkVersion }}
          docker buildx imagetools create ${{ env.IMAGE_NAME }}:dev-alpine-${{ matrix.openjdkVersion }} -t ${{ env.IMAGE_NAME }}:alpine-${{ matrix.openjdkVersion }}
          docker pull ${{ env.IMAGE_NAME }}:dev-ubuntu-${{ matrix.openjdkVersion }}
          docker buildx imagetools create ${{ env.IMAGE_NAME }}:dev-ubuntu-${{ matrix.openjdkVersion }} -t ${{ env.IMAGE_NAME }}:ubuntu-${{ matrix.openjdkVersion }}
          docker buildx imagetools create ${{ env.IMAGE_NAME }}:dev-ubuntu-${{ matrix.openjdkVersion }} -t ${{ env.IMAGE_NAME }}:${{ matrix.openjdkVersion }}
      - name: alpine, ubuntu, latest
        if: ${{ matrix.openjdkVersion == 'openjdk21' }}
        run: |
          docker buildx imagetools create ${{ env.IMAGE_NAME }}:dev-alpine-${{ matrix.openjdkVersion }} -t ${{ env.IMAGE_NAME }}:alpine
          docker buildx imagetools create ${{ env.IMAGE_NAME }}:dev-ubuntu-${{ matrix.openjdkVersion }} -t ${{ env.IMAGE_NAME }}:ubuntu
          docker buildx imagetools create ${{ env.IMAGE_NAME }}:dev-ubuntu-${{ matrix.openjdkVersion }} -t ${{ env.IMAGE_NAME }}:latest
      - name: Logout from Docker Hub
        run: docker logout
