name: Dockerhub-build

env:
  IMAGE_NAME: antlafarge/jdownloader

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.MD'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.MD'
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    strategy:
      matrix:
        max-parallel: [1]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: dev-alpine-openjdk8
        uses: docker/build-push-action@v6
        with:
          file: alpine-openjdk8.Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          tags: ${{ env.IMAGE_NAME }}:dev-alpine-openjdk8
          push: true
      -
        name: dev-ubuntu-openjdk8
        uses: docker/build-push-action@v6
        with:
          file: ubuntu-openjdk8.Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          tags: ${{ env.IMAGE_NAME }}:dev-ubuntu-openjdk8
          push: true
      -
        name: dev-alpine-openjdk17
        uses: docker/build-push-action@v6
        with:
          file: alpine-openjdk17.Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          tags: ${{ env.IMAGE_NAME }}:dev-alpine-openjdk17
          push: true
      -
        name: dev-ubuntu-openjdk17
        uses: docker/build-push-action@v6
        with:
          file: ubuntu-openjdk17.Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          tags: ${{ env.IMAGE_NAME }}:dev-ubuntu-openjdk17
          push: true
      -
        name: dev-alpine-openjdk21
        uses: docker/build-push-action@v6
        with:
          file: alpine-openjdk21.Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
          tags: ${{ env.IMAGE_NAME }}:dev-alpine-openjdk21
          push: true
      -
        name: dev-ubuntu-openjdk21
        uses: docker/build-push-action@v6
        with:
          file: ubuntu-openjdk21.Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          tags: ${{ env.IMAGE_NAME }}:dev-ubuntu-openjdk21
          push: true
